[build]
  command = "npm run build"
  publish = "build"

# Redirects for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_VERSION = "16.14.0"
